#include <iostream>

// TASK: The sequence of triangle numbers is generated by adding the natural
//		 numbers.  So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6
//		 + 7 = 28.  The 7th triangle number has 6 divisors: 1, 2, 4, 7, 14, 28.
//
//		 Find the value of the first triangle number that has over five hundred
//		 divisors.

int main()
{
	
}